<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo '<div class="form-group">';
echo $this->formRow($form->get('title')->setAttribute('class', 'form-control'));
echo '</div><div class="form-group">';
echo $this->formRow($form->get('artist')->setAttribute('class', 'form-control'));
echo '</div><div "="" class="btn-group">';
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
echo '</div>';
echo $this->form()->closeTag();